TiendaMVC/Tienda.WEB/Controllers/CestaController.cs
using System.Linq;
using System.Web.Mvc;
using Tienda.CORE.Contracts;
using Tienda.CORE.Models;

namespace Tienda.WEB.Controllers
{
    public class CestaController : Controller
    {
        IRepositorio<Cliente> clientes;
        ISCesta SerCesta;
        ISOrden serEnvio;

        public CestaController(ISCesta SCesta, ISOrden SEnvio, IRepositorio<Cliente> Clientes) {
            this.SerCesta = SCesta;
            this.serEnvio = SEnvio;
            this.clientes = Clientes;
        }
        // GET: Basket2
        public ActionResult Index()
        {
            var model = SerCesta.GetItemCesta(this.HttpContext);
            return View(model);
        }

        public ActionResult AgregarACesta(string Id)
        {
            SerCesta.AgregarACesta(this.HttpContext, Id);

            return RedirectToAction("Index");
        }

        public ActionResult RemoverDeLaCesta(string Id)
        {
            SerCesta.RemoverDeCesta(this.HttpContext, Id);

            return RedirectToAction("Index");
        }

        public PartialViewResult ResumenCesta() {
            var ResumenCesta = SerCesta.GetResumenCesta(this.HttpContext);

            return PartialView(ResumenCesta);
        }

        [Authorize]
        public ActionResult Comprar() {
            Cliente cliente = clientes.Collection().FirstOrDefault(c => c.CorreoCliente == User.Identity.Name);

            if (cliente != null)
            {

                OrdenEnvio orden = new OrdenEnvio()
                {
                    Correo = cliente.CorreoCliente,
                    Ciudad = cliente.CiudadCliente,
                    Provincia = cliente.ProvinciaCliente,
                    Calle = cliente.CalleCliente,
                    Nombre = cliente.NombreCliente,
                    Apellido = cliente.ApellidoCliente,
                    CodigoPostal = cliente.CodigoPostalCliente
                };

                return View(orden);
            }
            else {
                return RedirectToAction("Error");
            }
            
        }

        [HttpPost]
        [Authorize]
        public ActionResult Comprar(OrdenEnvio orden) {

            var ItemsCesta = SerCesta.GetItemCesta(this.HttpContext);
            orden.EstadoOrden = "Orden Creada";
            orden.Correo = User.Identity.Name;

            //proceso de pago

            orden.EstadoOrden = "Pago Procesado";
            serEnvio.CrearOrden(orden, ItemsCesta);
            SerCesta.LimpiarCesta(this.HttpContext);

            return RedirectToAction("Agradecimiento", new { OrderId = orden.Id });
        }

        public ActionResult Agradecimiento(string IdEnvio) {
            ViewBag.IdEnvio = IdEnvio;
            return View();
        }
    }
}

TiendaMVC/Tienda.WEB/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Tienda.CORE.Contracts;
using Tienda.CORE.Models;
using Tienda.CORE.ViewModels;

namespace Tienda.WEB.Controllers
{
    public class HomeController : Controller
    {
        IRepositorio<Producto> context;
        IRepositorio<CategProducto> CategoriasProductos;

        public HomeController(IRepositorio<Producto> productoContext, IRepositorio<CategProducto> productoCategoriaContext)
        {
            context = productoContext;
            CategoriasProductos = productoCategoriaContext;
        }

        public ActionResult Index(string Categoria=null)
        {
            List<Producto> productos;
            List<CategProducto> categorias = CategoriasProductos.Collection().ToList();

            if (Categoria == null)
            {
                productos = context.Collection().ToList();
            }
            else {
                productos = context.Collection().Where(p => p.Categoria == Categoria).ToList();
            }

            ListaProductosViewModel model = new ListaProductosViewModel();
            model.Productos = productos;
            model.CategoriaProducto = categorias;


            return View(model);
        }

        public ActionResult Detalles(string Id) {
            Producto producto = context.Buscar(Id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            else {
                return View(producto);
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TiendaMVC/Tienda.WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TiendaMVC/Tienda.WEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TiendaMVC/Tienda.WEB/Views/Home/Detalles.cshtml
@model Tienda.CORE.Models.Producto

@{
    ViewBag.Title = Model.Nombre + " Detalles";
}

<h2>@Html.DisplayFor(model=>model.Nombre)</h2>

<div>
    <div class="col-md-2">
        <img class="img-responsive" src="~/Content/ProductImages/@Model.Imagen"/>
    </div>
    <div class="col-md-10">
        <dl class="dl-horizontal">
          

            <dt>
                @Html.DisplayNameFor(model => model.Descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descripcion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Precio)
            </dt>

            <dd>
                $@Html.DisplayFor(model => model.Precio)
            </dd>

            <dt></dt>
            <dd><a href="@Url.Action("AgregarACesta", "Cesta", new { Id=Model.Id })" class="btn btn-default">Add To Basket</a></dd>

            <dt></dt>
            <dd>@Html.ActionLink("Back to List", "Index")</dd>
</dl>
    </div>
 </div>
<div class="col-md-12 clearfix"></div>

TiendaMVC/Tienda.WEB/Views/Home/Index.cshtml
@model Tienda.CORE.ViewModels.ListaProductosViewModel
@{
    ViewBag.Title = "Home Page";
}

<h1>Products</h1>

<div class="col-md-2">
    <h4>Filter by Category</h4>
    <div class="list-group">
        @Html.ActionLink("All", "Index", null, new { @class = Request["Categoria"] ==null? "list-group-item active" : "list-group-item"  })
        @foreach (var cat in Model.CategoriaProducto) {
            @Html.ActionLink(cat.Categoria, "Index", new { Categoria = cat.Categoria }, new { @class = Request["Categoria"] == cat.Categoria ? "list-group-item active" : "list-group-item" })
        }
    </div>
</div>
<div class="col-md-10">

    @foreach (var item in Model.Productos)
    {

        <div class="col-md-4" style="height:450px;padding:10px;margin:10px;border: solid thin whitesmoke">
            <div class="col-md-12">
                <img class="img" style="height:250px" src="~/Content/ProductImages/@item.Imagen" />
            </div>
            <div class="col-md-12">
                <strong>@Html.ActionLink(item.Nombre, "Detalles", new { id = item.Id })</strong>
            </div>
            <div class="col-md-12">
                <p>@item.Descripcion</p>
            </div>
            <div class="col-md-12">
                <h4>@item.Precio</h4>
            </div>
            <div class="col-md-12">
                <a href="@Url.Action("AgregarACesta", "Cesta", new { Id=item.Id })" class="btn btn-default">Add to Basket</a>
            </div>
        </div>
    }
</div>
<div class="col-md-12 clearfix"/>