TiendaMVC/Tienda.WEB/Controllers/AdminProductoController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Tienda.CORE.Models;
using Tienda.CORE.ViewModels;
using Tienda.CORE.Contracts;

namespace Tienda.WEB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminProductoController : Controller
    {
        IRepositorio<Producto> context;
        IRepositorio<CategProducto> Categoriasproductos;

        public AdminProductoController(IRepositorio<Producto> productoContext, IRepositorio<CategProducto> productCategoriaContext) {
            context = productoContext;
            Categoriasproductos = productCategoriaContext;
        }
        // GET: ProductManager
        public ActionResult Index()
        {
            List<Producto> productos = context.Collection().ToList();
            return View(productos);
        }

        public ActionResult Crear() {
            AdminProductoViewModel viewModel = new AdminProductoViewModel();

            viewModel.Producto = new Producto();
            viewModel.CategoriasProductos = Categoriasproductos.Collection();
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Crear(Producto producto, HttpPostedFileBase archivo) {
            if (!ModelState.IsValid)
            {
                return View(producto);
            }
            else {

                if (archivo != null) {
                    producto.Imagen = producto.Id + Path.GetExtension(archivo.FileName);
                    archivo.SaveAs(Server.MapPath("//Content//ProductImages//") + producto.Imagen);
                }

                context.Insertar(producto);
                context.Commit();

                return RedirectToAction("Index");
            }

        }

        public ActionResult Editar(string Id) {
            Producto producto = context.Buscar(Id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            else {
                AdminProductoViewModel viewModel = new AdminProductoViewModel();
                viewModel.Producto = producto;
                viewModel.CategoriasProductos = Categoriasproductos.Collection();

                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult Editar(Producto producto, string Id, HttpPostedFileBase archivo) {
            Producto ProductosHaEditar = context.Buscar(Id);

            if (ProductosHaEditar == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid) {
                    return View(producto);
                }

                if (archivo != null) {
                    ProductosHaEditar.Imagen = producto.Id + Path.GetExtension(archivo.FileName);
                    archivo.SaveAs(Server.MapPath("//Content//ProductImages//") + ProductosHaEditar.Imagen);
                }

                ProductosHaEditar.Categoria = producto.Categoria;
                ProductosHaEditar.Descripcion = producto.Descripcion;
                ProductosHaEditar.Nombre = producto.Nombre;
                ProductosHaEditar.Precio = producto.Precio;

                context.Commit();

                return RedirectToAction("Index");
            }
        }

        public ActionResult Eliminar(string Id)
        {
            Producto ProductosHaEliminar = context.Buscar(Id);

            if (ProductosHaEliminar == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(ProductosHaEliminar);
            }
        }

        [HttpPost]
        [ActionName("Eliminar")]
        public ActionResult ConfirmarParaEliminar(string Id) {
            Producto productosHaEliminar = context.Buscar(Id);

            if (productosHaEliminar == null)
            {
                return HttpNotFound();
            }
            else
            {
                context.Eliminar(Id);
                context.Commit();
                return RedirectToAction("Index");
            }
        }
    }
}

TiendaMVC/Tienda.WEB/Views/AdminProducto/Crear.cshtml
@model Tienda.CORE.ViewModels.AdminProductoViewModel

@{
    ViewBag.Title = "Crear";
}

<h2>Create</h2>


@using (Html.BeginForm("Crear", "AdminProducto", FormMethod.Post, new { encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Producto.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Producto.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Producto.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Producto.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Producto.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Producto.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Producto.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Producto.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Producto.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Producto.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model =>model.Producto.Categoria, new SelectList(Model.CategoriasProductos, "Categoria", "Categoria"), new { htmlAttributes = new { @class = "form-control" } })
                </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Producto.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="archivo" name="archivo" class="form-control" />    
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TiendaMVC/Tienda.WEB/Views/AdminProducto/Editar.cshtml
@model Tienda.CORE.ViewModels.AdminProductoViewModel

@{
    ViewBag.Title = "Editar";
}

<h2>Edit</h2>


@using (Html.BeginForm("Editar", "AdminProducto", FormMethod.Post, new { encType="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Producto.Id)

        <div class="col-md-2">
            <img class="img-responsive" src="~/Content/ProductImages/@Model.Producto.Imagen"/>
        </div>
        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Producto.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Producto.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Producto.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Producto.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Producto.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Producto.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Producto.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Producto.Precio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Producto.Precio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Producto.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Producto.Categoria, new SelectList(Model.CategoriasProductos, "Categoria", "Categoria"), new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Producto.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" id="archivo" name="archivo" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TiendaMVC/Tienda.WEB/Views/AdminProducto/Eliminar.cshtml
@model Tienda.CORE.Models.Producto

@{
    ViewBag.Title = "Eliminar";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagen)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TiendaMVC/Tienda.WEB/Views/AdminProducto/Index.cshtml
@model IEnumerable<Tienda.CORE.Models.Producto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Crear")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img class="img-thumbnail" style="height:50px" src="~/Content/ProductImages/@item.Imagen"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria)
        </td>
        <td>
            @Html.ActionLink("Edit", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Eliminar", new { id=item.Id })
        </td>
    </tr>
}

</table>